"""init

Revision ID: 81c391cc3780
Revises: 
Create Date: 2026-04-08 23:34:05.301175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c391cc3780'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ef_market_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('market_yes_price', sa.Float(), nullable=True),
    sa.Column('model_yes_prob', sa.Float(), nullable=True),
    sa.Column('edge_score', sa.Float(), nullable=True),
    sa.Column('kelly_fraction', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ef_market_edges_ticker'), 'ef_market_edges', ['ticker'], unique=False)
    op.create_table('ef_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('subscription_tier', sa.Enum('free', 'basic', 'pro', name='subscriptiontier'), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('kalshi_key_id', sa.String(), nullable=True),
    sa.Column('kalshi_private_key', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ef_users_email'), 'ef_users', ['email'], unique=True)
    op.create_table('ef_portfolio_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=True),
    sa.Column('snapped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ef_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ef_trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('kalshi_trade_id', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('market_title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('is_win', sa.Boolean(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ef_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ef_trades_kalshi_trade_id'), 'ef_trades', ['kalshi_trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ef_trades_kalshi_trade_id'), table_name='ef_trades')
    op.drop_table('ef_trades')
    op.drop_table('ef_portfolio_snapshots')
    op.drop_index(op.f('ix_ef_users_email'), table_name='ef_users')
    op.drop_table('ef_users')
    op.drop_index(op.f('ix_ef_market_edges_ticker'), table_name='ef_market_edges')
    op.drop_table('ef_market_edges')
    # ### end Alembic commands ###
